version: '3.6'
services:
  postgres:
    container_name: checkout_gateway_database
    image: postgres:13.8
    restart: unless-stopped
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_DB: checkoutdb
      POSTGRES_PASSWORD: defaultpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .postgres/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
